using Toybox.Application;
using Toybox.Application.Storage;
using Toybox.Attention;
using Toybox.FitContributor;
using Toybox.Lang;
using Toybox.Activity;
using Toybox.System;
using Toybox.Position;
using Toybox.Graphics;
using Toybox.Math;
using Toybox.WatchUi;

class RaceEstimatorView extends WatchUi.DataField {
  // Constants
  // Standard milestones + one optional custom distance (see MilestoneManager)
  private const MAX_MILESTONES = 10;
  private const STANDARD_COUNT = 9;
  private const DISPLAY_ROW_COUNT = 3; // Milestone window kept by MilestoneManager
  private const TOLERANCE_CM = 500;
  private const MIN_PREDICTION_DISTANCE = 100;
  private const POSITION_SHIFT_INTERVAL = 60; // ~1 min per AMOLED pixel-shift step

  // DEBUG: Ignore storage and always start fresh (automatically disabled in release builds)
  (:debug)
  private const DEBUG_IGNORE_STORAGE = true; // SIMULATOR: Always start fresh
  (:release)
  private const DEBUG_IGNORE_STORAGE = false; // PRODUCTION: Storage enabled

  // DEBUG: Enable verbose logging (automatically disabled in release builds)
  (:debug)
  private const DEBUG_LOGGING = true;
  (:release)
  private const DEBUG_LOGGING = false;

  // Full-screen layout (fractions of field height; text vertically centred)
  private const FS_TITLE_Y = 0.25;
  private const FS_HERO_Y = 0.40;
  private const FS_SUB_Y = 0.545;
  private const FS_ROW1_Y = 0.625;
  private const FS_ROW2_Y = 0.71;
  private const FS_TITLE_MAX_H = 0.09;
  private const FS_HERO_MAX_H = 0.22;
  private const FS_HERO_MAX_W = 0.64;
  private const FS_SUB_MAX_W = 0.8;
  // Compact layout (2/3/4-field)
  private const CP_TITLE_Y = 0.24;
  private const CP_VALUE_Y = 0.56;
  private const CP_BAR_Y = 0.86;
  private const CP_TITLE_MAX_H = 0.14;
  private const CP_VALUE_MAX_H = 0.45;
  private const CP_VALUE_MAX_W = 0.72;
  private const CP_BAR_MIN_FIELD_HEIGHT = 80;
  private const CP_BAR_BLOCKS = 10;
  private const BAR_WIDTH_PERCENT = 0.5;
  private const FULLSCREEN_THRESHOLD_PERCENT = 0.6; // Field taller than 60% of screen

  // Pixel font (resources/fonts, generated by tools/gen_pixel_font.py):
  // 5x7 glyphs; scale N means each glyph pixel is NxN screen pixels
  private const GLYPH_ROWS = 7;
  private const MIN_FONT_SCALE = 2;
  private const MAX_FONT_SCALE = 10;
  private const CHECK_GLYPH = "^";
  // Widest strings each role must fit
  private const HERO_SAMPLE = "00:00";
  private const HERO_LONG_SAMPLE = "0:00:00";
  private const TITLE_SAMPLE = "MARATHON";
  private const TABLE_SAMPLE = "^ MARATHON  0:00:00";
  private const SUB_SAMPLE = "00.00 KM IN 0:00:00";

  // Core business logic
  private var mMilestones as MilestoneManager;
  private var mPaceEstimator as PaceEstimator;
  private var mPersistence as PersistenceManager;
  private var mTimes as DisplayTextCache;
  private var mBurnInProtection as AmoledBurnInManager;
  private var mDataValidator as ActivityDataValidator;
  private var mColorScheme as ColorSchemeManager;
  private var mArc as ProgressArcDrawer;
  private var mStateDirty as Lang.Boolean = false;
  private var mErrorState as Lang.Number = 0;
  private var mConsecutiveErrors as Lang.Number = 0;
  private var mSafeModeCycles as Lang.Number = 0;

  // Restored state must be checked against the live timer once, so a stale
  // save from an activity that never got onTimerReset (crash, battery) is
  // not carried into the next run
  private var mRestoreChecked as Lang.Boolean = true;

  private var mIsAmoled as Lang.Boolean = false;
  private var mUseStatute as Lang.Boolean = false;

  // Validation thresholds
  private const MAX_CONSECUTIVE_ERRORS = 3;
  private const SAFE_MODE_RECOVERY_CYCLES = 10;
  private const MIN_DISTANCE_EPSILON = 0.1; // 10cm minimum distance
  private const MAX_TIME_MS = 359999000; // 99:59:59
  private const METERS_PER_MILE = 1609.344d;
  private const NOTICE_MS = 5000;
  private const STORAGE_KEY_SCALE = "distScale";

  // Coach alert setting (coachAlerts)
  private const ALERTS_OFF = 0;
  private const ALERTS_WARNINGS = 1;
  private const ALERTS_ALL = 2;

  // Per-second derived state shown by onUpdate
  private var mSubText as Lang.String = "";
  private var mSubIsStatus as Lang.Boolean = true;
  private var mSubIsCoach as Lang.Boolean = false;

  // Split scoring: each milestone's projection is snapshotted halfway through
  // its segment; on arrival the actual time is compared ("0:42 AHEAD")
  private const SNAPSHOT_AT_PROGRESS = 0.5d;
  private var mSnapshotMs as Lang.Array<Lang.Number?>;

  // Level map + race segmentation (target race from settings)
  private const DEFAULT_TARGET_IDX = 7; // Marathon
  private const CUSTOM_TARGET = 9; // targetRace value for "Custom"
  private const MIN_CUSTOM_KM = 1.0d;
  private const MAX_CUSTOM_KM = 250.0d;
  private var mTargetIdx as Lang.Number = DEFAULT_TARGET_IDX;
  private var mTargetCm as Lang.Number = 4219500;
  private var mGoalMs as Lang.Number = 0;
  private var mMapEndIdx as Lang.Number = DEFAULT_TARGET_IDX;
  private var mMapFraction as Lang.Double = 0.0d;
  private var mPhaseColors as Lang.Array<Lang.Number> = [0, 0, 0] as Lang.Array<Lang.Number>;

  // Race coach (segmentation + pace-aware messages), see CoachManager
  private var mCoach as CoachManager;
  private var mSegmentProgress as Lang.Double = 0.0d;
  private var mAlertsSetting as Lang.Number = ALERTS_WARNINGS;
  private var mLastCoachSeq as Lang.Number = 0;

  // Celebration frames cycled on the context line, 1 per second:
  // STAGE CLEAR! -> split -> NEW HIGH SCORE! -> ghost -> combo
  private var mCelebFrames as Lang.Array<Lang.String> = [] as Lang.Array<Lang.String>;
  private var mCelebColors as Lang.Array<Lang.Number> = [] as Lang.Array<Lang.Number>;

  // High scores and ghost (HighScores), results screen after the target
  private var mHighScores as HighScores;
  private var mTargetNewHigh as Lang.Boolean = false;
  private var mPrevBestMs as Lang.Number? = null;
  private var mShowResults as Lang.Boolean = false;
  // Attract mode until the timer starts, then "GO!" for the first seconds
  private const GO_MS = 4000;
  private var mStarted as Lang.Boolean = false;
  private var mAttractFrame as Lang.Number = 0;

  // Lap-button sync to course markers (DistanceCalibrator)
  private var mCalibrator as DistanceCalibrator;
  private var mLapSync as Lang.Boolean = false;
  private var mRawDistanceM as Lang.Double = 0.0d;
  private var mTimerMs as Lang.Number = 0;
  private var mNoticeText as Lang.String = "";
  private var mNoticeUntilMs as Lang.Number = 0;

  // Treadmill / indoor: no GPS gate, no altitude
  private var mIndoorChecked as Lang.Boolean = false;

  // FIT contributions (Garmin Connect charts)
  private var mFitProjected as FitContributor.Field?;
  private var mFitTarget as FitContributor.Field?;
  private var mFitVsGoal as FitContributor.Field?;

  // Layout (computed in onLayout)
  private var mIsFullScreen as Lang.Boolean = true;
  private var mCenterX as Lang.Number = 0;
  private var mFieldWidth as Lang.Number = 0;
  private var mFieldHeight as Lang.Number = 0;
  private var mTitleY as Lang.Number = 0;
  private var mHeroY as Lang.Number = 0;
  private var mSubY as Lang.Number = 0;
  private var mRow1Y as Lang.Number = 0;
  private var mRow2Y as Lang.Number = 0;
  private var mBarY as Lang.Number = 0;
  private var mTableHalfWidth as Lang.Number = 0;
  private var mHeroFont as Graphics.FontType = Graphics.FONT_NUMBER_MEDIUM;
  private var mHeroLongFont as Graphics.FontType = Graphics.FONT_NUMBER_MILD;
  private var mTitleFont as Graphics.FontType = Graphics.FONT_TINY;
  private var mSmallFont as Graphics.FontType = Graphics.FONT_XTINY;
  private var mSmallScale as Lang.Number = 2;
  private var mSubFont as Graphics.FontType = Graphics.FONT_XTINY;
  // Graphic sizes scale with the screen: 4px on a 260px fenix 7, 6px on a
  // 390/416px epix, so strokes don't shrink on high-density AMOLED panels
  private var mUnit as Lang.Number = 4;
  // Per-frame AMOLED pixel-shift offsets (always 0 on MIP)
  private var mOx as Lang.Number = 0;
  private var mOy as Lang.Number = 0;
  // Milestones shown in the two table rows under the hero (no per-frame alloc)
  private var mTableIdx as Lang.Array<Lang.Number> = [0, 0] as Lang.Array<Lang.Number>;

  private var mLastKnownBackground as Lang.Number = -1;
  private var mPhase as Lang.Number = 0;

  function initialize() {
    DataField.initialize();

    var settings = System.getDeviceSettings();
    if (settings has :requiresBurnInProtection) {
      mIsAmoled = settings.requiresBurnInProtection;
    }
    mUseStatute = settings.distanceUnits == System.UNIT_STATUTE;

    mMilestones = new MilestoneManager(
      STANDARD_COUNT,
      DISPLAY_ROW_COUNT,
      DEBUG_LOGGING
    );
    mPaceEstimator = new PaceEstimator(DEBUG_LOGGING);
    mPersistence = new PersistenceManager(DEBUG_LOGGING);
    mTimes = new DisplayTextCache(MAX_MILESTONES);
    mBurnInProtection = new AmoledBurnInManager(
      POSITION_SHIFT_INTERVAL,
      mIsAmoled,
      DEBUG_LOGGING
    );
    mDataValidator = new ActivityDataValidator(
      MIN_PREDICTION_DISTANCE,
      DEBUG_LOGGING
    );
    mColorScheme = new ColorSchemeManager(mIsAmoled, DEBUG_LOGGING);
    mArc = new ProgressArcDrawer(mIsAmoled);
    mSnapshotMs = new Lang.Array<Lang.Number?>[MAX_MILESTONES];
    mCoach = new CoachManager(mMilestones, mUseStatute);
    mHighScores = new HighScores(!DEBUG_IGNORE_STORAGE);
    mCalibrator = new DistanceCalibrator();
    loadSettings();

    loadFromStorage();
    mSubText = "GET READY";
  }

  // Called at start and from the app's onSettingsChanged
  function loadSettings() as Void {
    // Target: a standard distance, or a custom one inserted as an extra
    // milestone (finish times already recorded are kept)
    var target = readNumberSetting("targetRace", DEFAULT_TARGET_IDX);
    var customCm = 0;
    if (target == CUSTOM_TARGET) {
      var km = readFloatSetting("customDistanceKm", 15.0d);
      if (km < MIN_CUSTOM_KM) {
        km = MIN_CUSTOM_KM;
      } else if (km > MAX_CUSTOM_KM) {
        km = MAX_CUSTOM_KM;
      }
      customCm = (km * 100000.0d).toNumber();
      mTargetCm = customCm;
    } else {
      if (target < 0 || target >= STANDARD_COUNT) {
        target = DEFAULT_TARGET_IDX;
      }
      mTargetCm = MilestoneManager.STANDARD_CM[target] as Lang.Number;
    }
    var oldCount = mMilestones.getMilestoneCount();
    mMilestones.configure(customCm);
    if (mMilestones.getMilestoneCount() != oldCount) {
      // Indices shifted: per-index split snapshots no longer line up
      for (var i = 0; i < MAX_MILESTONES; i++) {
        mSnapshotMs[i] = null;
      }
    }
    mTargetIdx = mMilestones.indexOfDistance(mTargetCm);
    if (mTargetIdx < 0) {
      mTargetIdx = DEFAULT_TARGET_IDX;
    }
    mTargetCm = mMilestones.getMilestoneDistanceCm(mTargetIdx);
    mMilestones.setFanfareIdx(mTargetIdx);

    var hours = readNumberSetting("goalHours", 0);
    var minutes = readNumberSetting("goalMinutes", 0);
    var goalMin =
      (hours >= 0 && hours < 24 ? hours : 0) * 60 +
      (minutes >= 0 && minutes < 60 ? minutes : 0);
    mGoalMs = goalMin * 60000;
    mCoach.setGoalMs(mGoalMs);

    mCoach.setFuelInterval(readNumberSetting("fuelInterval", CoachManager.FUEL_AUTO));
    mAlertsSetting = readNumberSetting("coachAlerts", ALERTS_WARNINGS);
    mLapSync = readBooleanSetting("lapSync", false);

    // One-shot action: clear the high-score table and ghost
    if (readBooleanSetting("resetHighScores", false)) {
      mHighScores.clear();
      try {
        Application.Properties.setValue("resetHighScores", false);
      } catch (ex) {}
    }
  }

  private function readFloatSetting(
    key as Lang.String,
    fallback as Lang.Double
  ) as Lang.Double {
    try {
      var value = Application.Properties.getValue(key);
      if (value instanceof Lang.Float || value instanceof Lang.Double || value instanceof Lang.Number) {
        return value.toDouble();
      }
    } catch (ex) {}
    return fallback;
  }

  private function readBooleanSetting(
    key as Lang.String,
    fallback as Lang.Boolean
  ) as Lang.Boolean {
    try {
      var value = Application.Properties.getValue(key);
      if (value instanceof Lang.Boolean) {
        return value;
      }
    } catch (ex) {}
    return fallback;
  }

  // Projected finish (record) plus target time and goal margin (session),
  // charted in Garmin Connect; minutes so the chart axis reads naturally.
  // Called by the app right after construction (not from initialize, so
  // unit tests can build the view outside a recording activity)
  function createFitFields() as Void {
    try {
      mFitProjected = createField(
        "projected_finish",
        0,
        FitContributor.DATA_TYPE_FLOAT,
        { :mesgType => FitContributor.MESG_TYPE_RECORD, :units => "min" }
      );
      mFitTarget = createField(
        "target_time",
        1,
        FitContributor.DATA_TYPE_FLOAT,
        { :mesgType => FitContributor.MESG_TYPE_SESSION, :units => "min" }
      );
      mFitVsGoal = createField(
        "vs_goal",
        2,
        FitContributor.DATA_TYPE_FLOAT,
        { :mesgType => FitContributor.MESG_TYPE_SESSION, :units => "min" }
      );
    } catch (ex) {
      mFitProjected = null;
      mFitTarget = null;
      mFitVsGoal = null;
    }
  }

  private function writeFit(projectedMs as Lang.Number?) as Void {
    var targetMs = mMilestones.getMilestoneFinishTime(mTargetIdx);
    var shownMs = targetMs != null ? targetMs : projectedMs;
    if (shownMs == null) {
      return;
    }
    if (mFitProjected != null) {
      mFitProjected.setData(shownMs / 60000.0f);
    }
    if (targetMs != null) {
      if (mFitTarget != null) {
        mFitTarget.setData(targetMs / 60000.0f);
      }
      if (mFitVsGoal != null && mGoalMs > 0) {
        mFitVsGoal.setData((targetMs - mGoalMs) / 60000.0f);
      }
    }
  }

  private function readNumberSetting(
    key as Lang.String,
    fallback as Lang.Number
  ) as Lang.Number {
    try {
      var value = Application.Properties.getValue(key);
      if (value instanceof Lang.Number) {
        return value;
      }
    } catch (ex) {}
    return fallback;
  }

  // ---------------------------------------------------------------- compute

  function compute(info as Activity.Info) as Void {
    if (mErrorState == 1) {
      mSafeModeCycles++;
      if (mSafeModeCycles > SAFE_MODE_RECOVERY_CYCLES) {
        mErrorState = 0;
        mConsecutiveErrors = 0;
        mSafeModeCycles = 0;
      } else {
        return;
      }
    }

    try {
      computeImpl(info);
      mConsecutiveErrors = 0;
    } catch (ex) {
      mConsecutiveErrors++;
      if (DEBUG_LOGGING) {
        System.println(
          "Compute error #" + mConsecutiveErrors + ": " + ex.getErrorMessage()
        );
      }
      if (mConsecutiveErrors > MAX_CONSECUTIVE_ERRORS) {
        mErrorState = 1;
        mSafeModeCycles = 0;
        setStatus("SAFE MODE");
      }
    }
  }

  private function computeImpl(info as Activity.Info) as Void {
    var timerTimeMs = info.timerTime;
    var rawDistance = info.elapsedDistance;
    if (
      timerTimeMs == null ||
      timerTimeMs <= 0 ||
      rawDistance == null ||
      rawDistance < MIN_DISTANCE_EPSILON
    ) {
      return;
    }
    mTimerMs = timerTimeMs;
    mStarted = true;
    mRawDistanceM = rawDistance.toDouble();
    // Lap-sync correction (1.0 until a lap is pressed at a course marker)
    var elapsedDistance = mCalibrator.apply(mRawDistanceM).toFloat();

    if (!mIndoorChecked) {
      mIndoorChecked = true;
      var indoor = isIndoorActivity();
      mDataValidator.setIndoor(indoor);
      mPaceEstimator.setUseAltitude(!indoor);
    }

    // Stopped after the target: the results screen replaces PAUSED
    if (
      info.timerState == Activity.TIMER_STATE_PAUSED ||
      info.timerState == Activity.TIMER_STATE_STOPPED
    ) {
      mShowResults = mMilestones.getMilestoneFinishTime(mTargetIdx) != null;
      setStatus("PAUSED");
      return;
    }
    mShowResults = false;

    if (!mRestoreChecked) {
      mRestoreChecked = true;
      var times = mMilestones.getFinishTimesMs();
      for (var i = 0; i < times.size(); i++) {
        var t = times[i];
        if (t != null && t > timerTimeMs) {
          if (DEBUG_LOGGING) {
            System.println("Restored state is from another activity, discarding");
          }
          clearAllData();
          break;
        }
      }
    }

    // Milestone completion uses the watch's own (already filtered) distance,
    // so it must not be blocked by the GPS-quality gate below: a POOR fix at
    // the 10K mark would otherwise record a late split.
    if (
      mMilestones.checkAndMarkCompletions(
        elapsedDistance * 100.0d,
        timerTimeMs,
        TOLERANCE_CM
      )
    ) {
      mMilestones.rebuildDisplay();
      mStateDirty = true;
    }
    var live = mMilestones.consumeLiveCrossing();
    if (live != null) {
      onLiveCrossing(live);
    }
    if (mStateDirty) {
      saveToStorage();
    }

    // The pace model is fed every tick (the watch's distance is already
    // filtered) so its rolling window has no gaps; only showing predictions
    // is gated on GPS quality, minimum distance and warm-up
    var altitude = info.altitude;
    if (altitude != null) {
      mPaceEstimator.setAltitude(altitude.toDouble());
    }
    mPaceEstimator.update(timerTimeMs / 1000.0d, elapsedDistance.toDouble());
    var gpsOk = mDataValidator.validateGpsData(info);
    var canPredict =
      gpsOk &&
      mDataValidator.validateMinimumDistance(elapsedDistance) &&
      mPaceEstimator.isWarmedUp();

    // Every milestone shows a finish time: actual once reached, projected
    // (see PaceEstimator) before that
    var count = mMilestones.getMilestoneCount();
    var targetProjected = null;
    for (var i = 0; i < count; i++) {
      var finish = mMilestones.getMilestoneFinishTime(i);
      if (finish != null) {
        mTimes.setTime(i, finish);
      } else if (canPredict) {
        var projected =
          timerTimeMs +
          mPaceEstimator.estimateRemainingMs(
            mMilestones.getMilestoneDistanceCm(i) / 100.0d
          );
        if (projected > MAX_TIME_MS) {
          projected = MAX_TIME_MS;
        }
        mTimes.setTime(i, projected);
        if (i == mTargetIdx) {
          targetProjected = projected;
        }
        if (
          i == mMilestones.getNextMilestoneIdx() &&
          mSnapshotMs[i] == null &&
          mSegmentProgress >= SNAPSHOT_AT_PROGRESS
        ) {
          mSnapshotMs[i] = projected;
        }
      } else {
        mTimes.setPending(i);
      }
    }

    writeFit(targetProjected);

    updateMap(elapsedDistance);
    if (canPredict) {
      mCoach.update(
        timerTimeMs / 1000.0d,
        elapsedDistance.toDouble(),
        mTargetIdx,
        mMapFraction,
        mSegmentProgress,
        mPaceEstimator
      );
      alertOnNewMessage();
    }
    updateSegmentAndSubline(elapsedDistance, gpsOk, canPredict);
  }

  private function isIndoorActivity() as Lang.Boolean {
    if (!(Activity has :getProfileInfo)) {
      return false;
    }
    var profile = Activity.getProfileInfo();
    if (profile == null) {
      return false;
    }
    var sub = profile.subSport;
    return (
      sub == Activity.SUB_SPORT_TREADMILL ||
      sub == Activity.SUB_SPORT_INDOOR_RUNNING ||
      sub == Activity.SUB_SPORT_VIRTUAL_ACTIVITY
    );
  }

  // A milestone crossed live: high score, ghost and the celebration frames
  private function onLiveCrossing(idx as Lang.Number) as Void {
    var cm = mMilestones.getMilestoneDistanceCm(idx);
    var time = mMilestones.getMilestoneFinishTime(idx);
    if (time == null) {
      return;
    }
    var ghost = mHighScores.getGhost(mTargetCm, cm);
    var prevBest = mHighScores.getBest(cm);
    var improved = mHighScores.record(cm, time);
    var newHigh = improved && prevBest != null;

    if (idx == mTargetIdx) {
      mTargetNewHigh = newHigh;
      mPrevBestMs = prevBest;
      if (improved) {
        // This run becomes the ghost to race next time
        var splits = {} as Lang.Dictionary<Lang.Number, Lang.Number>;
        for (var i = 0; i <= mTargetIdx; i++) {
          var t = mMilestones.getMilestoneFinishTime(i);
          if (t != null) {
            splits.put(mMilestones.getMilestoneDistanceCm(i), t);
          }
        }
        mHighScores.setGhost(mTargetCm, splits);
      }
    }

    buildCelebration(idx, time, newHigh, ghost);
  }

  // Short buzz when the coach shows a new message (setting: off, warnings
  // only, all). Milestones have their own feedback in MilestoneManager.
  private function alertOnNewMessage() as Void {
    var seq = mCoach.getMessageSeq();
    if (seq == mLastCoachSeq) {
      return;
    }
    mLastCoachSeq = seq;
    var caution = mCoach.isCaution();
    if (
      mAlertsSetting == ALERTS_OFF ||
      (mAlertsSetting == ALERTS_WARNINGS && !caution)
    ) {
      return;
    }
    if ((Attention has :vibrate) && System.getDeviceSettings().vibrateOn) {
      Attention.vibrate(
        caution
          ? [
              new Attention.VibeProfile(75, 200),
              new Attention.VibeProfile(0, 100),
              new Attention.VibeProfile(75, 200),
            ]
          : [new Attention.VibeProfile(50, 120)]
      );
    }
  }

  // Lap pressed: if near a km / mile marker, sync distance to it
  function onTimerLap() as Void {
    if (!mLapSync) {
      return;
    }
    var unitM = mUseStatute ? METERS_PER_MILE : 1000.0d;
    var ratio = mCalibrator.onLap(mRawDistanceM, unitM);
    if (ratio <= 0.0d) {
      return;
    }
    mPaceEstimator.rescaleDistance(ratio);
    var marker = (mCalibrator.getLastMarkerM() / unitM + 0.5d).toNumber();
    showNotice("SYNC " + marker + (mUseStatute ? " MI" : " KM"));
    try {
      Storage.setValue(STORAGE_KEY_SCALE, mCalibrator.getScale().toFloat());
    } catch (ex) {}
  }

  private function showNotice(text as Lang.String) as Void {
    mNoticeText = text;
    mNoticeUntilMs = mTimerMs + NOTICE_MS;
  }

  // Map spans 0 -> target race; once the target is cleared it extends to the
  // next milestone ("bonus stage")
  private function updateMap(elapsedDistance as Lang.Float) as Void {
    var next = mMilestones.getNextMilestoneIdx();
    mMapEndIdx = next > mTargetIdx ? next : mTargetIdx;
    if (mMapEndIdx >= mMilestones.getMilestoneCount()) {
      mMapEndIdx = mMilestones.getMilestoneCount() - 1;
    }
    var endM = mMilestones.getMilestoneDistanceCm(mMapEndIdx) / 100.0d;
    mMapFraction = elapsedDistance / endM;
    if (mMapFraction > 1.0d) {
      mMapFraction = 1.0d;
    }
  }


  // Gauge fill and the one-line context under the hero:
  // "2.31 km in 11:04", or a status while not ready
  private function updateSegmentAndSubline(
    elapsedDistance as Lang.Float,
    gpsOk as Lang.Boolean,
    canPredict as Lang.Boolean
  ) as Void {
    var next = mMilestones.getNextMilestoneIdx();
    if (next >= mMilestones.getMilestoneCount()) {
      mSegmentProgress = 1.0d;
      setStatus("ALL CLEAR!");
      return;
    }

    var nextM = mMilestones.getMilestoneDistanceCm(next) / 100.0d;
    var prevM =
      next > 0 ? mMilestones.getMilestoneDistanceCm(next - 1) / 100.0d : 0.0d;
    mSegmentProgress = (elapsedDistance - prevM) / (nextM - prevM);
    if (mSegmentProgress < 0.0d) {
      mSegmentProgress = 0.0d;
    } else if (mSegmentProgress > 1.0d) {
      mSegmentProgress = 1.0d;
    }

    if (mMilestones.isCelebrating()) {
      setStatus(
        mMilestones.getCelebrationMilestoneIdx() == mTargetIdx
          ? "TARGET CLEAR!"
          : "STAGE CLEAR!"
      );
      return;
    }
    if (mNoticeText.length() > 0) {
      if (mTimerMs <= mNoticeUntilMs) {
        setStatus(mNoticeText);
        return;
      }
      mNoticeText = "";
    }
    if (!gpsOk) {
      setStatus("WAITING FOR GPS");
      return;
    }
    var message = mCoach.getMessage();
    if (message.length() > 0) {
      mSubText = message;
      mSubIsStatus = true;
      mSubIsCoach = true;
      return;
    }

    var remainingM = nextM - elapsedDistance;
    if (remainingM < 0.0d) {
      remainingM = 0.0d;
    }
    var dist = mUseStatute
      ? remainingM / METERS_PER_MILE
      : remainingM / 1000.0d;
    var distText = dist.format("%.2f") + (mUseStatute ? " MI" : " KM");

    if (!canPredict) {
      mSubText = distText + " TO GO";
    mSubIsCoach = false;
    } else {
      var remainingMs = mPaceEstimator.estimateRemainingMs(nextM);
      if (remainingMs > MAX_TIME_MS) {
        remainingMs = MAX_TIME_MS;
      }
      mSubText = distText + " IN " + formatDuration(remainingMs);
      mSubIsCoach = false;
    }
    mSubIsStatus = false;
  }

  // Celebration frames for a milestone crossed live: its split against the
  // halfway projection ("0:42 AHEAD"), a new high score, the ghost
  // ("GHOST -0:40" = ahead of your best run) and the combo streak
  private function buildCelebration(
    idx as Lang.Number,
    actual as Lang.Number,
    newHigh as Lang.Boolean,
    ghost as Lang.Number?
  ) as Void {
    mCelebFrames = [] as Lang.Array<Lang.String>;
    mCelebColors = [] as Lang.Array<Lang.Number>;
    // Frame 0 is the live status ("STAGE CLEAR!"); colour -1 = status colour
    mCelebFrames.add("");
    mCelebColors.add(-1);

    var predicted = mSnapshotMs[idx];
    if (predicted != null) {
      var delta = actual - predicted;
      var ahead = delta <= 0;
      mCoach.onSplit(ahead);
      mCelebFrames.add(
        formatDuration(delta < 0 ? -delta : delta) + (ahead ? " AHEAD" : " BEHIND")
      );
      mCelebColors.add(ahead ? 1 : 2);
    } else {
      mCelebFrames.add(""); // blink
      mCelebColors.add(0);
    }
    if (newHigh) {
      mCelebFrames.add("NEW HIGH SCORE!");
      mCelebColors.add(3);
    }
    if (ghost != null) {
      var g = actual - ghost;
      mCelebFrames.add(
        "GHOST " + (g <= 0 ? "-" : "+") + formatDuration(g < 0 ? -g : g)
      );
      mCelebColors.add(g <= 0 ? 1 : 2);
    }
    var combo = mCoach.getComboText();
    if (combo.length() > 0) {
      mCelebFrames.add(combo);
      mCelebColors.add(3);
    }
  }

  private function setStatus(text as Lang.String) as Void {
    mSubText = text;
    mSubIsStatus = true;
    mSubIsCoach = false;
  }

  // Read-only state for tests and diagnostics
  function getSubText() as Lang.String {
    return mSubText;
  }

  function isShowingResults() as Lang.Boolean {
    return mShowResults;
  }

  function getTargetIdx() as Lang.Number {
    return mTargetIdx;
  }

  // ----------------------------------------------------------------- layout

  function onLayout(dc as Graphics.Dc) as Void {
    var w = dc.getWidth();
    var h = dc.getHeight();
    var deviceSettings = System.getDeviceSettings();

    mFieldWidth = w;
    mFieldHeight = h;
    mCenterX = w / 2;
    mUnit = deviceSettings.screenWidth / 65;
    if (mUnit < 3) {
      mUnit = 3;
    }
    mIsFullScreen =
      h > deviceSettings.screenHeight * FULLSCREEN_THRESHOLD_PERCENT;
    mArc.setGeometry(w, h);

    var heroMaxW = 0;
    var heroMaxH = 0;
    var titleMaxH = 0;
    var smallMaxW = 0;
    if (mIsFullScreen) {
      mTitleY = (h * FS_TITLE_Y).toNumber();
      mHeroY = (h * FS_HERO_Y).toNumber();
      mSubY = (h * FS_SUB_Y).toNumber();
      mRow1Y = (h * FS_ROW1_Y).toNumber();
      mRow2Y = (h * FS_ROW2_Y).toNumber();
      heroMaxW = (w * FS_HERO_MAX_W).toNumber();
      heroMaxH = (h * FS_HERO_MAX_H).toNumber();
      titleMaxH = (h * FS_TITLE_MAX_H).toNumber();

      // Table columns: as wide as the circle allows at the lowest row,
      // identical for both rows so labels and values line up
      var inner = mArc.getInnerRadius() - mUnit;
      var dy = mRow2Y + h / 20 - h / 2;
      var sq = inner * inner - dy * dy;
      mTableHalfWidth = sq > 0 ? Math.sqrt(sq).toNumber() - mUnit : w / 3;
      if (mTableHalfWidth > (w * 0.38).toNumber()) {
        mTableHalfWidth = (w * 0.38).toNumber();
      }
      smallMaxW = mTableHalfWidth * 2;
      var subMaxW = (w * FS_SUB_MAX_W).toNumber();
      if (smallMaxW > subMaxW) {
        smallMaxW = subMaxW;
      }
    } else {
      mTitleY = (h * CP_TITLE_Y).toNumber();
      mHeroY = (h * CP_VALUE_Y).toNumber();
      mBarY = (h * CP_BAR_Y).toNumber();
      heroMaxW = (w * CP_VALUE_MAX_W).toNumber();
      heroMaxH = (h * CP_VALUE_MAX_H).toNumber();
      titleMaxH = (h * CP_TITLE_MAX_H).toNumber();
      smallMaxW = w;
    }

    mHeroFont = loadPixelFont(fitScale(HERO_SAMPLE, heroMaxW, heroMaxH));
    mHeroLongFont = loadPixelFont(fitScale(HERO_LONG_SAMPLE, heroMaxW, heroMaxH));
    mTitleFont = loadPixelFont(fitScale(TITLE_SAMPLE, w / 2, titleMaxH));
    mSmallScale = fitScale(TABLE_SAMPLE, smallMaxW, h);
    mSmallFont = loadPixelFont(mSmallScale);
    // Context line: fits the longest coach message across the circle's
    // chord at that height, capped at the table size for visual rhythm
    var subCols = pixelColumns(SUB_SAMPLE);
    if (subCols < CoachManager.MAX_COLUMNS) {
      subCols = CoachManager.MAX_COLUMNS;
    }
    var subMax = (w * FS_SUB_MAX_W).toNumber();
    if (mIsFullScreen) {
      var r = mArc.getInnerRadius();
      var dy = mSubY - h / 2;
      var sq = r * r - dy * dy;
      if (sq > 0 && Math.sqrt(sq).toNumber() * 2 < subMax) {
        subMax = Math.sqrt(sq).toNumber() * 2;
      }
    }
    var subScale = subMax / subCols;
    if (subScale > mSmallScale) {
      subScale = mSmallScale;
    }
    if (subScale < MIN_FONT_SCALE) {
      subScale = MIN_FONT_SCALE;
    }
    mSubFont = loadPixelFont(subScale);
  }

  // Largest integer scale at which `sample` fits the box
  private function fitScale(
    sample as Lang.String,
    maxWidth as Lang.Number,
    maxHeight as Lang.Number
  ) as Lang.Number {
    var byWidth = maxWidth / pixelColumns(sample);
    var byHeight = maxHeight / GLYPH_ROWS;
    var scale = byWidth < byHeight ? byWidth : byHeight;
    if (scale < MIN_FONT_SCALE) {
      return MIN_FONT_SCALE;
    }
    return scale > MAX_FONT_SCALE ? MAX_FONT_SCALE : scale;
  }

  // Solid glyphs on MIP (contrast), dot-matrix glyphs on AMOLED from scale 4
  // (fewer lit pixels = less power and burn-in); see tools/gen_pixel_font.py
  private function loadPixelFont(scale as Lang.Number) as Graphics.FontType {
    var id = null;
    if (mIsAmoled && scale >= 4) {
      var dots =
        [
          Rez.Fonts.Dot4,
          Rez.Fonts.Dot5,
          Rez.Fonts.Dot6,
          Rez.Fonts.Dot7,
          Rez.Fonts.Dot8,
          Rez.Fonts.Dot9,
          Rez.Fonts.Dot10,
        ] as Lang.Array<Lang.ResourceId>;
      id = dots[scale - 4];
    } else {
      var solid =
        [
          Rez.Fonts.Pixel2,
          Rez.Fonts.Pixel3,
          Rez.Fonts.Pixel4,
          Rez.Fonts.Pixel5,
          Rez.Fonts.Pixel6,
          Rez.Fonts.Pixel7,
          Rez.Fonts.Pixel8,
          Rez.Fonts.Pixel9,
          Rez.Fonts.Pixel10,
        ] as Lang.Array<Lang.ResourceId>;
      id = solid[scale - MIN_FONT_SCALE];
    }
    return WatchUi.loadResource(id) as Graphics.FontReference;
  }

  // ----------------------------------------------------------------- render

  function onUpdate(dc as Graphics.Dc) as Void {
    var bg = getBackgroundColor();
    if (bg != mLastKnownBackground) {
      mLastKnownBackground = bg;
      mColorScheme.updateColors(bg);
    }

    dc.setColor(
      mColorScheme.getValueColor(),
      mColorScheme.getBackgroundColor()
    );
    dc.clear();

    mBurnInProtection.update();
    mOx = mBurnInProtection.getOffsetX();
    mOy = mBurnInProtection.getOffsetY();

    // 1 Hz animation phase (data fields redraw once a second; nothing faster
    // is needed or spent)
    mPhase = (System.getTimer() / 1000) % 2;

    var focus = mMilestones.getFocusIdx();
    if (mShowResults) {
      focus = mTargetIdx;
    }
    if (mIsFullScreen && !mStarted) {
      drawAttract(dc);
    } else if (mIsFullScreen && mShowResults) {
      drawResults(dc);
    } else if (mIsFullScreen) {
      drawFullScreen(dc, focus);
    } else {
      drawCompact(dc, focus);
    }
  }

  //   [segmented gauge]      10K               <- title, check when reached
  //                         48:12              <- projected / actual finish
  //                   2.31 KM IN 11:04         <- context or arcade status
  //                  HALF ........ 1:46:20     <- hi-score table
  //                  MARATHON .... 3:44:05
  private function drawFullScreen(dc as Graphics.Dc, focus as Lang.Number) as Void {
    var celebrating = mMilestones.isCelebrating();
    drawLevelMap(dc, celebrating);

    drawTitle(dc, focus);
    drawHero(dc, focus);
    drawSubline(dc, celebrating);

    selectTableRows(focus);
    var left = mCenterX - mTableHalfWidth + mOx;
    var right = mCenterX + mTableHalfWidth + mOx;
    drawTableRow(dc, mTableIdx[0], mRow1Y + mOy, left, right);
    drawTableRow(dc, mTableIdx[1], mRow2Y + mOy, left, right);
  }

  // Arc = level map of the target race: travelled blocks in phase colours,
  // milestone pips (cleared / next, blinking / future), boss pip at the end,
  // player marker at the current distance
  private function drawLevelMap(dc as Graphics.Dc, celebrating as Lang.Boolean) as Void {
    mPhaseColors[0] = mColorScheme.getLabelColor();
    mPhaseColors[1] = mColorScheme.getProgressColor();
    mPhaseColors[2] = mColorScheme.getTitleColor();
    mArc.draw(
      dc,
      mMapFraction,
      mPhaseColors,
      mColorScheme.getTrackColor(),
      mOx,
      mOy,
      celebrating ? mPhase : -1
    );

    var endCm = mMilestones.getMilestoneDistanceCm(mMapEndIdx).toDouble();
    var next = mMilestones.getNextMilestoneIdx();
    for (var i = 0; i <= mMapEndIdx; i++) {
      var color = mColorScheme.getTrackColor();
      if (i < next) {
        color = mColorScheme.getProgressColor();
      } else if (i == next) {
        if (mPhase == 1 && !celebrating) {
          continue; // next pip blinks at 1 Hz
        }
        color = mColorScheme.getTitleColor();
      } else if (i == mMapEndIdx) {
        color = mColorScheme.getStatusColor(); // boss
      }
      mArc.drawPip(
        dc,
        mMilestones.getMilestoneDistanceCm(i) / endCm,
        color,
        i == mMapEndIdx,
        mOx,
        mOy
      );
    }

    mArc.drawPlayer(
      dc,
      mMapFraction,
      mColorScheme.getValueColor(),
      mColorScheme.getBackgroundColor(),
      mOx,
      mOy
    );
  }

  // Context line. While celebrating it alternates each second between
  // "STAGE CLEAR!" and the split result (or blinks if there is none).
  private function drawSubline(dc as Graphics.Dc, celebrating as Lang.Boolean) as Void {
    var text = mSubText;
    var color = mColorScheme.getLabelColor();
    if (mSubIsCoach) {
      color = mCoach.isCaution()
        ? mColorScheme.getStatusColor()
        : mColorScheme.getTitleColor();
    } else if (mSubIsStatus) {
      color = mColorScheme.getStatusColor();
    }

    // Celebration cycles 1 frame per second (see buildCelebration)
    var frames = mCelebFrames.size();
    if (celebrating && frames > 0) {
      var frame = (System.getTimer() / 1000) % frames;
      if (frame > 0) {
        text = mCelebFrames[frame];
        if (text.length() == 0) {
          return; // blink
        }
        color = celebColor(mCelebColors[frame]);
      }
    }

    dc.setColor(color, Graphics.COLOR_TRANSPARENT);
    dc.drawText(
      mCenterX + mOx,
      mSubY + mOy,
      mSubFont,
      text,
      Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER
    );
  }

  //   [arc chase]            MARATHON
  //                          READY           <- blinks
  //                       PRESS START
  //                  HI-SCORE ....... 3:41:05
  //                  GOAL ........... 3:30:00
  // Arcade attract mode before the timer starts: the level map fills in a
  // chase, one step per second (the field only redraws at 1 Hz)
  private function drawAttract(dc as Graphics.Dc) as Void {
    mAttractFrame = (mAttractFrame + 1) % 28;
    mPhaseColors[0] = mColorScheme.getLabelColor();
    mPhaseColors[1] = mColorScheme.getProgressColor();
    mPhaseColors[2] = mColorScheme.getTitleColor();
    mArc.draw(
      dc,
      mAttractFrame / 27.0d,
      mPhaseColors,
      mColorScheme.getTrackColor(),
      mOx,
      mOy,
      -1
    );
    mArc.drawPlayer(
      dc,
      mAttractFrame / 27.0d,
      mColorScheme.getValueColor(),
      mColorScheme.getBackgroundColor(),
      mOx,
      mOy
    );
    drawTitle(dc, mTargetIdx);
    var center = Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER;
    if (mPhase == 0) {
      dc.setColor(mColorScheme.getValueColor(), Graphics.COLOR_TRANSPARENT);
      dc.drawText(mCenterX + mOx, mHeroY + mOy, mHeroLongFont, "READY", center);
    }
    dc.setColor(mColorScheme.getStatusColor(), Graphics.COLOR_TRANSPARENT);
    dc.drawText(mCenterX + mOx, mSubY + mOy, mSubFont, "PRESS START", center);

    var left = mCenterX - mTableHalfWidth + mOx;
    var right = mCenterX + mTableHalfWidth + mOx;
    var best = mHighScores.getBest(mTargetCm);
    drawRow(dc, "HI-SCORE", best != null ? formatDuration(best) : "--:--", false, mRow1Y + mOy, left, right);
    drawRow(dc, "GOAL", mGoalMs > 0 ? formatDuration(mGoalMs) : "--:--", false, mRow2Y + mOy, left, right);
  }

  // 1 ahead / good, 2 behind, 3 title (gold), else label
  private function celebColor(code as Lang.Number) as Lang.Number {
    if (code == 1) {
      return mColorScheme.getProgressColor();
    } else if (code == 2) {
      return mColorScheme.getStatusColor();
    } else if (code == 3) {
      return mColorScheme.getTitleColor();
    }
    return mColorScheme.getLabelColor();
  }

  //   [full level map]        MARATHON           <- target, checked
  //                           3:41:05            <- final time
  //                        NEW HIGH SCORE!       <- verdict / goal margin
  //                  OLD BEST ....... 3:44:10
  //                  MAX COMBO ............ X3
  // Shown while the timer is stopped after the target was reached
  private function drawResults(dc as Graphics.Dc) as Void {
    drawLevelMap(dc, false);
    drawTitle(dc, mTargetIdx);
    drawHero(dc, mTargetIdx);

    var time = mMilestones.getMilestoneFinishTime(mTargetIdx);
    var verdict = "GAME OVER";
    var verdictColor = mColorScheme.getStatusColor();
    if (mTargetNewHigh) {
      verdict = "NEW HIGH SCORE!";
      verdictColor = mColorScheme.getTitleColor();
    } else if (mGoalMs > 0 && time != null && time <= mGoalMs) {
      verdict = "GOAL CLEAR!";
      verdictColor = mColorScheme.getProgressColor();
    }
    // Alternate with the goal margin every other second
    if (mGoalMs > 0 && time != null && mPhase == 1) {
      var d = time - mGoalMs;
      verdict = formatDuration(d < 0 ? -d : d) + (d <= 0 ? " UNDER GOAL" : " OVER GOAL");
      verdictColor = d <= 0 ? mColorScheme.getProgressColor() : mColorScheme.getStatusColor();
    }
    dc.setColor(verdictColor, Graphics.COLOR_TRANSPARENT);
    dc.drawText(
      mCenterX + mOx,
      mSubY + mOy,
      mSubFont,
      verdict,
      Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER
    );

    var left = mCenterX - mTableHalfWidth + mOx;
    var right = mCenterX + mTableHalfWidth + mOx;
    // Best before this run when it was beaten, so both numbers are visible
    var best = mTargetNewHigh ? mPrevBestMs : mHighScores.getBest(mTargetCm);
    drawRow(
      dc,
      mTargetNewHigh ? "OLD BEST" : "HI-SCORE",
      best != null ? formatDuration(best) : "--:--",
      false,
      mRow1Y + mOy,
      left,
      right
    );
    drawRow(
      dc,
      "MAX COMBO",
      "X" + mCoach.getMaxCombo(),
      false,
      mRow2Y + mOy,
      left,
      right
    );
  }

  // Native-style single value: title on top, auto-sized number, and a
  // segmented energy bar when the field is tall enough
  private function drawCompact(dc as Graphics.Dc, focus as Lang.Number) as Void {
    drawTitle(dc, focus);
    drawHero(dc, focus);

    if (mFieldHeight < CP_BAR_MIN_FIELD_HEIGHT) {
      return;
    }
    var barWidth = (mFieldWidth * BAR_WIDTH_PERCENT).toNumber();
    var pitch = barWidth / CP_BAR_BLOCKS;
    var block = pitch - mUnit / 2 - 1;
    var barHeight = mUnit + 1;
    var x = mCenterX - (pitch * CP_BAR_BLOCKS) / 2 + mOx;
    var y = mBarY + mOy;
    var progress =
      mMilestones.getMilestoneFinishTime(focus) != null ||
      mMilestones.isAllComplete()
        ? 1.0d
        : mSegmentProgress;
    var lit = (progress * CP_BAR_BLOCKS).toNumber();
    var marquee = mMilestones.isCelebrating();

    for (var i = 0; i < CP_BAR_BLOCKS; i++) {
      var on = marquee ? i % 2 == mPhase : i < lit;
      if (!on && mIsAmoled) {
        continue;
      }
      dc.setColor(
        on ? mColorScheme.getProgressColor() : mColorScheme.getTrackColor(),
        Graphics.COLOR_TRANSPARENT
      );
      dc.fillRectangle(x + i * pitch, y, block, barHeight);
    }
  }

  // Milestone name; a reached milestone gets a check glyph in front
  private function drawTitle(dc as Graphics.Dc, focus as Lang.Number) as Void {
    var label = mMilestones.getMilestoneLabel(focus);
    var y = mTitleY + mOy;
    var justify = Graphics.TEXT_JUSTIFY_LEFT | Graphics.TEXT_JUSTIFY_VCENTER;
    var labelWidth = dc.getTextWidthInPixels(label, mTitleFont);
    var checkWidth = 0;
    var done = mMilestones.getMilestoneFinishTime(focus) != null;
    if (done) {
      checkWidth = dc.getTextWidthInPixels(CHECK_GLYPH + " ", mTitleFont);
    }
    var x = mCenterX - (checkWidth + labelWidth) / 2 + mOx;
    if (done) {
      dc.setColor(mColorScheme.getProgressColor(), Graphics.COLOR_TRANSPARENT);
      dc.drawText(x, y, mTitleFont, CHECK_GLYPH, justify);
    }
    dc.setColor(mColorScheme.getTitleColor(), Graphics.COLOR_TRANSPARENT);
    dc.drawText(x + checkWidth, y, mTitleFont, label, justify);
  }

  // Big finish time; the H:MM:SS form uses the next size down so it fits
  private function drawHero(dc as Graphics.Dc, focus as Lang.Number) as Void {
    var time = mTimes.getTime(focus);
    if (mStarted && mTimerMs < GO_MS && !mShowResults) {
      time = "GO!";
    }
    dc.setColor(mColorScheme.getValueColor(), Graphics.COLOR_TRANSPARENT);
    dc.drawText(
      mCenterX + mOx,
      mHeroY + mOy,
      time.length() > 5 ? mHeroLongFont : mHeroFont,
      time,
      Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER
    );
  }

  // Two rows under the hero: the next two milestones; near the end, fall back
  // to the most recent results so the table never goes blank
  private function selectTableRows(focus as Lang.Number) as Void {
    var count = mMilestones.getMilestoneCount();
    if (focus + 2 < count) {
      mTableIdx[0] = focus + 1;
      mTableIdx[1] = focus + 2;
    } else if (focus + 1 < count) {
      mTableIdx[0] = focus - 1;
      mTableIdx[1] = focus + 1;
    } else {
      mTableIdx[0] = focus - 2;
      mTableIdx[1] = focus - 1;
    }
  }

  // Milestone row of the hi-score table
  private function drawTableRow(
    dc as Graphics.Dc,
    idx as Lang.Number,
    y as Lang.Number,
    left as Lang.Number,
    right as Lang.Number
  ) as Void {
    drawRow(
      dc,
      mMilestones.getMilestoneLabel(idx),
      mTimes.getTime(idx),
      mMilestones.getMilestoneFinishTime(idx) != null,
      y,
      left,
      right
    );
  }

  // Hi-score row: LABEL ....... TIME, dots one glyph-pixel in size
  private function drawRow(
    dc as Graphics.Dc,
    label as Lang.String,
    time as Lang.String,
    checked as Lang.Boolean,
    y as Lang.Number,
    left as Lang.Number,
    right as Lang.Number
  ) as Void {
    var justify = Graphics.TEXT_JUSTIFY_LEFT | Graphics.TEXT_JUSTIFY_VCENTER;
    var x = left;
    if (checked) {
      dc.setColor(mColorScheme.getProgressColor(), Graphics.COLOR_TRANSPARENT);
      dc.drawText(x, y, mSmallFont, CHECK_GLYPH, justify);
      x += dc.getTextWidthInPixels(CHECK_GLYPH + " ", mSmallFont);
    }
    dc.setColor(mColorScheme.getLabelColor(), Graphics.COLOR_TRANSPARENT);
    dc.drawText(x, y, mSmallFont, label, justify);

    // Leader dots, aligned to a 2-glyph-pixel grid so both rows match
    var s = mSmallScale;
    var dotsFrom = x + dc.getTextWidthInPixels(label, mSmallFont) + 2 * s;
    var dotsTo = right - dc.getTextWidthInPixels(time, mSmallFont) - 2 * s;
    var dotX = left + ((dotsFrom - left + 2 * s - 1) / (2 * s)) * (2 * s);
    dc.setColor(mColorScheme.getTrackColor(), Graphics.COLOR_TRANSPARENT);
    while (dotX + s <= dotsTo) {
      dc.fillRectangle(dotX, y + s, s, s);
      dotX += 2 * s;
    }

    dc.setColor(mColorScheme.getValueColor(), Graphics.COLOR_TRANSPARENT);
    dc.drawText(
      right,
      y,
      mSmallFont,
      time,
      Graphics.TEXT_JUSTIFY_RIGHT | Graphics.TEXT_JUSTIFY_VCENTER
    );
  }

  // ------------------------------------------------------------ persistence

  // Saves only on milestone events; the dirty flag is kept on failure so the
  // next compute (or pause/stop) retries instead of silently dropping state
  private function saveToStorage() as Void {
    if (mPersistence.saveFinishTimes(mMilestones.getFinishTimesMs())) {
      mStateDirty = false;
    }
  }

  private function loadFromStorage() as Void {
    if (DEBUG_IGNORE_STORAGE) {
      clearAllData();
      return;
    }

    var loadedTimes = mPersistence.loadFinishTimes(mMilestones.getMilestoneCount());
    if (loadedTimes != null && mMilestones.setFinishTimesMs(loadedTimes)) {
      mMilestones.rebuildDisplay();
      mTimes.reset();
      mRestoreChecked = false;
      try {
        var scale = Storage.getValue(STORAGE_KEY_SCALE);
        if (scale instanceof Lang.Float || scale instanceof Lang.Double) {
          mCalibrator.setScale(scale.toDouble());
        }
      } catch (ex) {}
    } else {
      clearAllData();
    }
  }

  private function clearAllData() as Void {
    mMilestones.reset();
    mTimes.reset();
    mPersistence.clearStorage();
    mStateDirty = false;
    mSegmentProgress = 0.0d;
    for (var i = 0; i < MAX_MILESTONES; i++) {
      mSnapshotMs[i] = null;
    }
    mCelebFrames = [] as Lang.Array<Lang.String>;
    mCelebColors = [] as Lang.Array<Lang.Number>;
    mMapFraction = 0.0d;
    mCoach.reset();
    mLastCoachSeq = 0;
    mCalibrator.reset();
    mTargetNewHigh = false;
    mPrevBestMs = null;
    mShowResults = false;
    mNoticeText = "";
    mIndoorChecked = false;
    mStarted = false;
    try {
      Storage.deleteValue(STORAGE_KEY_SCALE);
    } catch (ex) {}
  }

  function onTimerPause() as Void {
    if (mStateDirty) {
      saveToStorage();
    }
  }

  function onTimerStop() as Void {
    if (mStateDirty) {
      saveToStorage();
    }
  }

  function onTimerReset() as Void {
    clearAllData();
    mRestoreChecked = true;
    mBurnInProtection.reset();
    mPaceEstimator.reset();
    mDataValidator.reset();
    setStatus("GET READY");
  }
}
