using Toybox.Lang;
using Toybox.Activity;
using Toybox.System;
using Toybox.Position;
using Toybox.Graphics;
using Toybox.Math;
using Toybox.WatchUi;

class RaceEstimatorView extends WatchUi.DataField {
  // Constants
  private const MILESTONE_COUNT = 9;
  private const DISPLAY_ROW_COUNT = 3; // Milestone window kept by MilestoneManager
  private const TOLERANCE_CM = 500;
  private const MIN_PREDICTION_DISTANCE = 100;
  private const POSITION_SHIFT_INTERVAL = 60; // ~1 min per AMOLED pixel-shift step

  // DEBUG: Ignore storage and always start fresh (automatically disabled in release builds)
  (:debug)
  private const DEBUG_IGNORE_STORAGE = true; // SIMULATOR: Always start fresh
  (:release)
  private const DEBUG_IGNORE_STORAGE = false; // PRODUCTION: Storage enabled

  // DEBUG: Enable verbose logging (automatically disabled in release builds)
  (:debug)
  private const DEBUG_LOGGING = true;
  (:release)
  private const DEBUG_LOGGING = false;

  // Full-screen layout (fractions of field height; text vertically centred)
  private const FS_TITLE_Y = 0.23;
  private const FS_HERO_Y = 0.40;
  private const FS_SUB_Y = 0.56;
  private const FS_ROW1_Y = 0.67;
  private const FS_ROW2_Y = 0.77;
  private const FS_TITLE_MAX_H = 0.09;
  private const FS_HERO_MAX_H = 0.22;
  private const FS_HERO_MAX_W = 0.64;
  private const FS_SUB_MAX_W = 0.8;
  // Compact layout (2/3/4-field)
  private const CP_TITLE_Y = 0.24;
  private const CP_VALUE_Y = 0.56;
  private const CP_BAR_Y = 0.86;
  private const CP_TITLE_MAX_H = 0.14;
  private const CP_VALUE_MAX_H = 0.45;
  private const CP_VALUE_MAX_W = 0.72;
  private const CP_BAR_MIN_FIELD_HEIGHT = 80;
  private const CP_BAR_BLOCKS = 10;
  private const BAR_WIDTH_PERCENT = 0.5;
  private const FULLSCREEN_THRESHOLD_PERCENT = 0.6; // Field taller than 60% of screen

  // Pixel font (resources/fonts, generated by tools/gen_pixel_font.py):
  // 5x7 glyphs; scale N means each glyph pixel is NxN screen pixels
  private const GLYPH_ROWS = 7;
  private const MIN_FONT_SCALE = 2;
  private const MAX_FONT_SCALE = 10;
  private const CHECK_GLYPH = "^";
  // Widest strings each role must fit
  private const HERO_SAMPLE = "00:00";
  private const HERO_LONG_SAMPLE = "0:00:00";
  private const TITLE_SAMPLE = "MARATHON";
  private const TABLE_SAMPLE = "^ MARATHON  0:00:00";
  private const SUB_SAMPLE = "00.00 KM IN 0:00:00";

  // Core business logic
  private var mMilestones as MilestoneManager;
  private var mPaceEstimator as PaceEstimator;
  private var mPersistence as PersistenceManager;
  private var mTimes as DisplayTextCache;
  private var mBurnInProtection as AmoledBurnInManager;
  private var mDataValidator as ActivityDataValidator;
  private var mColorScheme as ColorSchemeManager;
  private var mArc as ProgressArcDrawer;
  private var mStateDirty as Lang.Boolean = false;
  private var mErrorState as Lang.Number = 0;
  private var mConsecutiveErrors as Lang.Number = 0;
  private var mSafeModeCycles as Lang.Number = 0;

  // Restored state must be checked against the live timer once, so a stale
  // save from an activity that never got onTimerReset (crash, battery) is
  // not carried into the next run
  private var mRestoreChecked as Lang.Boolean = true;

  private var mIsAmoled as Lang.Boolean = false;
  private var mUseStatute as Lang.Boolean = false;

  // Validation thresholds
  private const MAX_CONSECUTIVE_ERRORS = 3;
  private const SAFE_MODE_RECOVERY_CYCLES = 10;
  private const MIN_DISTANCE_EPSILON = 0.1; // 10cm minimum distance
  private const MAX_TIME_MS = 359999000; // 99:59:59
  private const METERS_PER_MILE = 1609.344d;

  // Per-second derived state shown by onUpdate
  private var mSubText as Lang.String = "";
  private var mSubIsStatus as Lang.Boolean = true;

  // Split scoring: each milestone's projection is snapshotted halfway through
  // its segment; on arrival the actual time is compared ("0:42 AHEAD")
  private const SNAPSHOT_AT_PROGRESS = 0.5d;
  private var mSnapshotMs as Lang.Array<Lang.Number?>;
  private var mSplitText as Lang.String = "";
  private var mSplitAhead as Lang.Boolean = true;
  private var mSplitShownFor as Lang.Number = -1;
  private var mSegmentProgress as Lang.Double = 0.0d;

  // Layout (computed in onLayout)
  private var mIsFullScreen as Lang.Boolean = true;
  private var mCenterX as Lang.Number = 0;
  private var mFieldWidth as Lang.Number = 0;
  private var mFieldHeight as Lang.Number = 0;
  private var mTitleY as Lang.Number = 0;
  private var mHeroY as Lang.Number = 0;
  private var mSubY as Lang.Number = 0;
  private var mRow1Y as Lang.Number = 0;
  private var mRow2Y as Lang.Number = 0;
  private var mBarY as Lang.Number = 0;
  private var mTableHalfWidth as Lang.Number = 0;
  private var mHeroFont as Graphics.FontType = Graphics.FONT_NUMBER_MEDIUM;
  private var mHeroLongFont as Graphics.FontType = Graphics.FONT_NUMBER_MILD;
  private var mTitleFont as Graphics.FontType = Graphics.FONT_TINY;
  private var mSmallFont as Graphics.FontType = Graphics.FONT_XTINY;
  private var mSmallScale as Lang.Number = 2;
  // Graphic sizes scale with the screen: 4px on a 260px fenix 7, 6px on a
  // 390/416px epix, so strokes don't shrink on high-density AMOLED panels
  private var mUnit as Lang.Number = 4;
  // Per-frame AMOLED pixel-shift offsets (always 0 on MIP)
  private var mOx as Lang.Number = 0;
  private var mOy as Lang.Number = 0;
  // Milestones shown in the two table rows under the hero (no per-frame alloc)
  private var mTableIdx as Lang.Array<Lang.Number> = [0, 0] as Lang.Array<Lang.Number>;

  private var mLastKnownBackground as Lang.Number = -1;
  private var mPhase as Lang.Number = 0;

  function initialize() {
    DataField.initialize();

    var settings = System.getDeviceSettings();
    if (settings has :requiresBurnInProtection) {
      mIsAmoled = settings.requiresBurnInProtection;
    }
    mUseStatute = settings.distanceUnits == System.UNIT_STATUTE;

    mMilestones = new MilestoneManager(
      MILESTONE_COUNT,
      DISPLAY_ROW_COUNT,
      DEBUG_LOGGING
    );
    mPaceEstimator = new PaceEstimator(DEBUG_LOGGING);
    mPersistence = new PersistenceManager(DEBUG_LOGGING);
    mTimes = new DisplayTextCache(MILESTONE_COUNT);
    mBurnInProtection = new AmoledBurnInManager(
      POSITION_SHIFT_INTERVAL,
      mIsAmoled,
      DEBUG_LOGGING
    );
    mDataValidator = new ActivityDataValidator(
      MIN_PREDICTION_DISTANCE,
      DEBUG_LOGGING
    );
    mColorScheme = new ColorSchemeManager(mIsAmoled, DEBUG_LOGGING);
    mArc = new ProgressArcDrawer(mIsAmoled);
    mSnapshotMs = new Lang.Array<Lang.Number?>[MILESTONE_COUNT];

    loadFromStorage();
    mSubText = "GET READY";
  }

  // ---------------------------------------------------------------- compute

  function compute(info as Activity.Info) as Void {
    if (mErrorState == 1) {
      mSafeModeCycles++;
      if (mSafeModeCycles > SAFE_MODE_RECOVERY_CYCLES) {
        mErrorState = 0;
        mConsecutiveErrors = 0;
        mSafeModeCycles = 0;
      } else {
        return;
      }
    }

    try {
      computeImpl(info);
      mConsecutiveErrors = 0;
    } catch (ex) {
      mConsecutiveErrors++;
      if (DEBUG_LOGGING) {
        System.println(
          "Compute error #" + mConsecutiveErrors + ": " + ex.getErrorMessage()
        );
      }
      if (mConsecutiveErrors > MAX_CONSECUTIVE_ERRORS) {
        mErrorState = 1;
        mSafeModeCycles = 0;
        setStatus("SAFE MODE");
      }
    }
  }

  private function computeImpl(info as Activity.Info) as Void {
    var timerTimeMs = info.timerTime;
    var elapsedDistance = info.elapsedDistance;
    if (
      timerTimeMs == null ||
      timerTimeMs <= 0 ||
      elapsedDistance == null ||
      elapsedDistance < MIN_DISTANCE_EPSILON
    ) {
      return;
    }

    if (
      info.timerState == Activity.TIMER_STATE_PAUSED ||
      info.timerState == Activity.TIMER_STATE_STOPPED
    ) {
      setStatus("PAUSED");
      return;
    }

    if (!mRestoreChecked) {
      mRestoreChecked = true;
      var times = mMilestones.getFinishTimesMs();
      for (var i = 0; i < times.size(); i++) {
        var t = times[i];
        if (t != null && t > timerTimeMs) {
          if (DEBUG_LOGGING) {
            System.println("Restored state is from another activity, discarding");
          }
          clearAllData();
          break;
        }
      }
    }

    // Milestone completion uses the watch's own (already filtered) distance,
    // so it must not be blocked by the GPS-quality gate below: a POOR fix at
    // the 10K mark would otherwise record a late split.
    if (
      mMilestones.checkAndMarkCompletions(
        elapsedDistance * 100.0d,
        timerTimeMs,
        TOLERANCE_CM
      )
    ) {
      mMilestones.rebuildDisplay();
      mStateDirty = true;
    }
    if (mStateDirty) {
      saveToStorage();
    }

    // The pace model is fed every tick (the watch's distance is already
    // filtered) so its rolling window has no gaps; only showing predictions
    // is gated on GPS quality, minimum distance and warm-up
    mPaceEstimator.update(timerTimeMs / 1000.0d, elapsedDistance.toDouble());
    var gpsOk = mDataValidator.validateGpsData(info);
    var canPredict =
      gpsOk &&
      mDataValidator.validateMinimumDistance(elapsedDistance) &&
      mPaceEstimator.isWarmedUp();

    // Every milestone shows a finish time: actual once reached, projected
    // (see PaceEstimator) before that
    for (var i = 0; i < MILESTONE_COUNT; i++) {
      var finish = mMilestones.getMilestoneFinishTime(i);
      if (finish != null) {
        mTimes.setTime(i, finish);
      } else if (canPredict) {
        var projected =
          timerTimeMs +
          mPaceEstimator.estimateRemainingMs(
            mMilestones.getMilestoneDistanceCm(i) / 100.0d
          );
        if (projected > MAX_TIME_MS) {
          projected = MAX_TIME_MS;
        }
        mTimes.setTime(i, projected);
        if (
          i == mMilestones.getNextMilestoneIdx() &&
          mSnapshotMs[i] == null &&
          mSegmentProgress >= SNAPSHOT_AT_PROGRESS
        ) {
          mSnapshotMs[i] = projected;
        }
      } else {
        mTimes.setPending(i);
      }
    }

    updateSegmentAndSubline(elapsedDistance, gpsOk, canPredict);
  }

  // Gauge fill and the one-line context under the hero:
  // "2.31 km in 11:04", or a status while not ready
  private function updateSegmentAndSubline(
    elapsedDistance as Lang.Float,
    gpsOk as Lang.Boolean,
    canPredict as Lang.Boolean
  ) as Void {
    var next = mMilestones.getNextMilestoneIdx();
    if (next >= MILESTONE_COUNT) {
      mSegmentProgress = 1.0d;
      setStatus("ALL CLEAR!");
      return;
    }

    var nextM = mMilestones.getMilestoneDistanceCm(next) / 100.0d;
    var prevM =
      next > 0 ? mMilestones.getMilestoneDistanceCm(next - 1) / 100.0d : 0.0d;
    mSegmentProgress = (elapsedDistance - prevM) / (nextM - prevM);
    if (mSegmentProgress < 0.0d) {
      mSegmentProgress = 0.0d;
    } else if (mSegmentProgress > 1.0d) {
      mSegmentProgress = 1.0d;
    }

    if (mMilestones.isCelebrating()) {
      updateSplitText();
      setStatus("STAGE CLEAR!");
      return;
    }
    if (!gpsOk) {
      setStatus("WAITING FOR GPS");
      return;
    }

    var remainingM = nextM - elapsedDistance;
    if (remainingM < 0.0d) {
      remainingM = 0.0d;
    }
    var dist = mUseStatute
      ? remainingM / METERS_PER_MILE
      : remainingM / 1000.0d;
    var distText = dist.format("%.2f") + (mUseStatute ? " MI" : " KM");

    if (!canPredict) {
      mSubText = distText + " TO GO";
    } else {
      var remainingMs = mPaceEstimator.estimateRemainingMs(nextM);
      if (remainingMs > MAX_TIME_MS) {
        remainingMs = MAX_TIME_MS;
      }
      mSubText = distText + " IN " + formatDuration(remainingMs);
    }
    mSubIsStatus = false;
  }

  // Formats the celebrated milestone's result against its halfway projection,
  // once per celebration
  private function updateSplitText() as Void {
    var idx = mMilestones.getCelebrationMilestoneIdx();
    if (idx == null || idx == mSplitShownFor) {
      return;
    }
    mSplitShownFor = idx;
    mSplitText = "";
    var predicted = mSnapshotMs[idx];
    var actual = mMilestones.getMilestoneFinishTime(idx);
    if (predicted == null || actual == null) {
      return;
    }
    var delta = actual - predicted;
    mSplitAhead = delta <= 0;
    mSplitText =
      formatDuration(delta < 0 ? -delta : delta) +
      (mSplitAhead ? " AHEAD" : " BEHIND");
  }

  private function setStatus(text as Lang.String) as Void {
    mSubText = text;
    mSubIsStatus = true;
  }

  // ----------------------------------------------------------------- layout

  function onLayout(dc as Graphics.Dc) as Void {
    var w = dc.getWidth();
    var h = dc.getHeight();
    var deviceSettings = System.getDeviceSettings();

    mFieldWidth = w;
    mFieldHeight = h;
    mCenterX = w / 2;
    mUnit = deviceSettings.screenWidth / 65;
    if (mUnit < 3) {
      mUnit = 3;
    }
    mIsFullScreen =
      h > deviceSettings.screenHeight * FULLSCREEN_THRESHOLD_PERCENT;
    mArc.setGeometry(w, h);

    var heroMaxW = 0;
    var heroMaxH = 0;
    var titleMaxH = 0;
    var smallMaxW = 0;
    if (mIsFullScreen) {
      mTitleY = (h * FS_TITLE_Y).toNumber();
      mHeroY = (h * FS_HERO_Y).toNumber();
      mSubY = (h * FS_SUB_Y).toNumber();
      mRow1Y = (h * FS_ROW1_Y).toNumber();
      mRow2Y = (h * FS_ROW2_Y).toNumber();
      heroMaxW = (w * FS_HERO_MAX_W).toNumber();
      heroMaxH = (h * FS_HERO_MAX_H).toNumber();
      titleMaxH = (h * FS_TITLE_MAX_H).toNumber();

      // Table columns: as wide as the circle allows at the lowest row,
      // identical for both rows so labels and values line up
      var inner = mArc.getInnerRadius() - mUnit;
      var dy = mRow2Y + h / 20 - h / 2;
      var sq = inner * inner - dy * dy;
      mTableHalfWidth = sq > 0 ? Math.sqrt(sq).toNumber() - mUnit : w / 3;
      if (mTableHalfWidth > (w * 0.38).toNumber()) {
        mTableHalfWidth = (w * 0.38).toNumber();
      }
      smallMaxW = mTableHalfWidth * 2;
      var subMaxW = (w * FS_SUB_MAX_W).toNumber();
      if (smallMaxW > subMaxW) {
        smallMaxW = subMaxW;
      }
    } else {
      mTitleY = (h * CP_TITLE_Y).toNumber();
      mHeroY = (h * CP_VALUE_Y).toNumber();
      mBarY = (h * CP_BAR_Y).toNumber();
      heroMaxW = (w * CP_VALUE_MAX_W).toNumber();
      heroMaxH = (h * CP_VALUE_MAX_H).toNumber();
      titleMaxH = (h * CP_TITLE_MAX_H).toNumber();
      smallMaxW = w;
    }

    mHeroFont = loadPixelFont(fitScale(HERO_SAMPLE, heroMaxW, heroMaxH));
    mHeroLongFont = loadPixelFont(fitScale(HERO_LONG_SAMPLE, heroMaxW, heroMaxH));
    mTitleFont = loadPixelFont(fitScale(TITLE_SAMPLE, w / 2, titleMaxH));
    mSmallScale = fitScale(TABLE_SAMPLE, smallMaxW, h);
    var subScale = fitScale(SUB_SAMPLE, smallMaxW, h);
    if (subScale < mSmallScale) {
      mSmallScale = subScale;
    }
    mSmallFont = loadPixelFont(mSmallScale);
  }

  // Largest integer scale at which `sample` fits the box
  private function fitScale(
    sample as Lang.String,
    maxWidth as Lang.Number,
    maxHeight as Lang.Number
  ) as Lang.Number {
    var byWidth = maxWidth / pixelColumns(sample);
    var byHeight = maxHeight / GLYPH_ROWS;
    var scale = byWidth < byHeight ? byWidth : byHeight;
    if (scale < MIN_FONT_SCALE) {
      return MIN_FONT_SCALE;
    }
    return scale > MAX_FONT_SCALE ? MAX_FONT_SCALE : scale;
  }

  // Width of a string in glyph-pixel columns (mirrors gen_pixel_font.py)
  private function pixelColumns(text as Lang.String) as Lang.Number {
    var chars = text.toCharArray();
    var cols = 0;
    for (var i = 0; i < chars.size(); i++) {
      var c = chars[i];
      if (c == ':' || c == '.' || c == '!' || c == '\'') {
        cols += 2;
      } else if (c == ' ' || c == ',') {
        cols += 3;
      } else if (c == 'I') {
        cols += 4;
      } else if (c == '-') {
        cols += 5;
      } else {
        cols += 6;
      }
    }
    return cols > 1 ? cols - 1 : 1;
  }

  // Solid glyphs on MIP (contrast), dot-matrix glyphs on AMOLED from scale 4
  // (fewer lit pixels = less power and burn-in); see tools/gen_pixel_font.py
  private function loadPixelFont(scale as Lang.Number) as Graphics.FontType {
    var id = null;
    if (mIsAmoled && scale >= 4) {
      var dots =
        [
          Rez.Fonts.Dot4,
          Rez.Fonts.Dot5,
          Rez.Fonts.Dot6,
          Rez.Fonts.Dot7,
          Rez.Fonts.Dot8,
          Rez.Fonts.Dot9,
          Rez.Fonts.Dot10,
        ] as Lang.Array<Lang.ResourceId>;
      id = dots[scale - 4];
    } else {
      var solid =
        [
          Rez.Fonts.Pixel2,
          Rez.Fonts.Pixel3,
          Rez.Fonts.Pixel4,
          Rez.Fonts.Pixel5,
          Rez.Fonts.Pixel6,
          Rez.Fonts.Pixel7,
          Rez.Fonts.Pixel8,
          Rez.Fonts.Pixel9,
          Rez.Fonts.Pixel10,
        ] as Lang.Array<Lang.ResourceId>;
      id = solid[scale - MIN_FONT_SCALE];
    }
    return WatchUi.loadResource(id) as Graphics.FontReference;
  }

  // ----------------------------------------------------------------- render

  function onUpdate(dc as Graphics.Dc) as Void {
    var bg = getBackgroundColor();
    if (bg != mLastKnownBackground) {
      mLastKnownBackground = bg;
      mColorScheme.updateColors(bg);
    }

    dc.setColor(
      mColorScheme.getValueColor(),
      mColorScheme.getBackgroundColor()
    );
    dc.clear();

    mBurnInProtection.update();
    mOx = mBurnInProtection.getOffsetX();
    mOy = mBurnInProtection.getOffsetY();

    // 1 Hz animation phase (data fields redraw once a second; nothing faster
    // is needed or spent)
    mPhase = (System.getTimer() / 1000) % 2;

    var focus = mMilestones.getFocusIdx();
    if (mIsFullScreen) {
      drawFullScreen(dc, focus);
    } else {
      drawCompact(dc, focus);
    }
  }

  //   [segmented gauge]      10K               <- title, check when reached
  //                         48:12              <- projected / actual finish
  //                   2.31 KM IN 11:04         <- context or arcade status
  //                  HALF ........ 1:46:20     <- hi-score table
  //                  MARATHON .... 3:44:05
  private function drawFullScreen(dc as Graphics.Dc, focus as Lang.Number) as Void {
    var gaugeProgress =
      mMilestones.isCelebrating() || mMilestones.isAllComplete()
        ? 1.0d
        : mSegmentProgress;
    var celebrating = mMilestones.isCelebrating();
    mArc.draw(
      dc,
      gaugeProgress,
      mColorScheme.getProgressColor(),
      mColorScheme.getTrackColor(),
      mOx,
      mOy,
      celebrating ? mPhase : -1
    );

    drawTitle(dc, focus);
    drawHero(dc, focus);
    drawSubline(dc, celebrating);

    selectTableRows(focus);
    var left = mCenterX - mTableHalfWidth + mOx;
    var right = mCenterX + mTableHalfWidth + mOx;
    drawTableRow(dc, mTableIdx[0], mRow1Y + mOy, left, right);
    drawTableRow(dc, mTableIdx[1], mRow2Y + mOy, left, right);
  }

  // Context line. While celebrating it alternates each second between
  // "STAGE CLEAR!" and the split result (or blinks if there is none).
  private function drawSubline(dc as Graphics.Dc, celebrating as Lang.Boolean) as Void {
    var text = mSubText;
    var color = mSubIsStatus
      ? mColorScheme.getStatusColor()
      : mColorScheme.getLabelColor();
    if (celebrating && mPhase == 1) {
      if (mSplitText.length() == 0) {
        return;
      }
      text = mSplitText;
      color = mSplitAhead
        ? mColorScheme.getProgressColor()
        : mColorScheme.getStatusColor();
    }
    dc.setColor(color, Graphics.COLOR_TRANSPARENT);
    dc.drawText(
      mCenterX + mOx,
      mSubY + mOy,
      mSmallFont,
      text,
      Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER
    );
  }

  // Native-style single value: title on top, auto-sized number, and a
  // segmented energy bar when the field is tall enough
  private function drawCompact(dc as Graphics.Dc, focus as Lang.Number) as Void {
    drawTitle(dc, focus);
    drawHero(dc, focus);

    if (mFieldHeight < CP_BAR_MIN_FIELD_HEIGHT) {
      return;
    }
    var barWidth = (mFieldWidth * BAR_WIDTH_PERCENT).toNumber();
    var pitch = barWidth / CP_BAR_BLOCKS;
    var block = pitch - mUnit / 2 - 1;
    var barHeight = mUnit + 1;
    var x = mCenterX - (pitch * CP_BAR_BLOCKS) / 2 + mOx;
    var y = mBarY + mOy;
    var progress =
      mMilestones.getMilestoneFinishTime(focus) != null ||
      mMilestones.isAllComplete()
        ? 1.0d
        : mSegmentProgress;
    var lit = (progress * CP_BAR_BLOCKS).toNumber();
    var marquee = mMilestones.isCelebrating();

    for (var i = 0; i < CP_BAR_BLOCKS; i++) {
      var on = marquee ? i % 2 == mPhase : i < lit;
      if (!on && mIsAmoled) {
        continue;
      }
      dc.setColor(
        on ? mColorScheme.getProgressColor() : mColorScheme.getTrackColor(),
        Graphics.COLOR_TRANSPARENT
      );
      dc.fillRectangle(x + i * pitch, y, block, barHeight);
    }
  }

  // Milestone name; a reached milestone gets a check glyph in front
  private function drawTitle(dc as Graphics.Dc, focus as Lang.Number) as Void {
    var label = mMilestones.getMilestoneLabel(focus);
    var y = mTitleY + mOy;
    var justify = Graphics.TEXT_JUSTIFY_LEFT | Graphics.TEXT_JUSTIFY_VCENTER;
    var labelWidth = dc.getTextWidthInPixels(label, mTitleFont);
    var checkWidth = 0;
    var done = mMilestones.getMilestoneFinishTime(focus) != null;
    if (done) {
      checkWidth = dc.getTextWidthInPixels(CHECK_GLYPH + " ", mTitleFont);
    }
    var x = mCenterX - (checkWidth + labelWidth) / 2 + mOx;
    if (done) {
      dc.setColor(mColorScheme.getProgressColor(), Graphics.COLOR_TRANSPARENT);
      dc.drawText(x, y, mTitleFont, CHECK_GLYPH, justify);
    }
    dc.setColor(mColorScheme.getTitleColor(), Graphics.COLOR_TRANSPARENT);
    dc.drawText(x + checkWidth, y, mTitleFont, label, justify);
  }

  // Big finish time; the H:MM:SS form uses the next size down so it fits
  private function drawHero(dc as Graphics.Dc, focus as Lang.Number) as Void {
    var time = mTimes.getTime(focus);
    dc.setColor(mColorScheme.getValueColor(), Graphics.COLOR_TRANSPARENT);
    dc.drawText(
      mCenterX + mOx,
      mHeroY + mOy,
      time.length() > 5 ? mHeroLongFont : mHeroFont,
      time,
      Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER
    );
  }

  // Two rows under the hero: the next two milestones; near the end, fall back
  // to the most recent results so the table never goes blank
  private function selectTableRows(focus as Lang.Number) as Void {
    if (focus + 2 < MILESTONE_COUNT) {
      mTableIdx[0] = focus + 1;
      mTableIdx[1] = focus + 2;
    } else if (focus + 1 < MILESTONE_COUNT) {
      mTableIdx[0] = focus - 1;
      mTableIdx[1] = focus + 1;
    } else {
      mTableIdx[0] = focus - 2;
      mTableIdx[1] = focus - 1;
    }
  }

  // Hi-score row: LABEL ....... TIME, dots one glyph-pixel in size
  private function drawTableRow(
    dc as Graphics.Dc,
    idx as Lang.Number,
    y as Lang.Number,
    left as Lang.Number,
    right as Lang.Number
  ) as Void {
    var justify = Graphics.TEXT_JUSTIFY_LEFT | Graphics.TEXT_JUSTIFY_VCENTER;
    var x = left;
    if (mMilestones.getMilestoneFinishTime(idx) != null) {
      dc.setColor(mColorScheme.getProgressColor(), Graphics.COLOR_TRANSPARENT);
      dc.drawText(x, y, mSmallFont, CHECK_GLYPH, justify);
      x += dc.getTextWidthInPixels(CHECK_GLYPH + " ", mSmallFont);
    }
    var label = mMilestones.getMilestoneLabel(idx);
    var time = mTimes.getTime(idx);
    dc.setColor(mColorScheme.getLabelColor(), Graphics.COLOR_TRANSPARENT);
    dc.drawText(x, y, mSmallFont, label, justify);

    // Leader dots, aligned to a 2-glyph-pixel grid so both rows match
    var s = mSmallScale;
    var dotsFrom = x + dc.getTextWidthInPixels(label, mSmallFont) + 2 * s;
    var dotsTo = right - dc.getTextWidthInPixels(time, mSmallFont) - 2 * s;
    var dotX = left + ((dotsFrom - left + 2 * s - 1) / (2 * s)) * (2 * s);
    dc.setColor(mColorScheme.getTrackColor(), Graphics.COLOR_TRANSPARENT);
    while (dotX + s <= dotsTo) {
      dc.fillRectangle(dotX, y + s, s, s);
      dotX += 2 * s;
    }

    dc.setColor(mColorScheme.getValueColor(), Graphics.COLOR_TRANSPARENT);
    dc.drawText(
      right,
      y,
      mSmallFont,
      time,
      Graphics.TEXT_JUSTIFY_RIGHT | Graphics.TEXT_JUSTIFY_VCENTER
    );
  }

  // ------------------------------------------------------------ persistence

  // Saves only on milestone events; the dirty flag is kept on failure so the
  // next compute (or pause/stop) retries instead of silently dropping state
  private function saveToStorage() as Void {
    if (mPersistence.saveFinishTimes(mMilestones.getFinishTimesMs())) {
      mStateDirty = false;
    }
  }

  private function loadFromStorage() as Void {
    if (DEBUG_IGNORE_STORAGE) {
      clearAllData();
      return;
    }

    var loadedTimes = mPersistence.loadFinishTimes(MILESTONE_COUNT);
    if (loadedTimes != null && mMilestones.setFinishTimesMs(loadedTimes)) {
      mMilestones.rebuildDisplay();
      mTimes.reset();
      mRestoreChecked = false;
    } else {
      clearAllData();
    }
  }

  private function clearAllData() as Void {
    mMilestones.reset();
    mTimes.reset();
    mPersistence.clearStorage();
    mStateDirty = false;
    mSegmentProgress = 0.0d;
    for (var i = 0; i < MILESTONE_COUNT; i++) {
      mSnapshotMs[i] = null;
    }
    mSplitShownFor = -1;
    mSplitText = "";
  }

  function onTimerPause() as Void {
    if (mStateDirty) {
      saveToStorage();
    }
  }

  function onTimerStop() as Void {
    if (mStateDirty) {
      saveToStorage();
    }
  }

  function onTimerReset() as Void {
    clearAllData();
    mRestoreChecked = true;
    mBurnInProtection.reset();
    mPaceEstimator.reset();
    mDataValidator.reset();
    setStatus("GET READY");
  }
}
